import {  Dimensions } from 'react-native';

export default {
  numberPinguin:10,
  durationMove:100,
  screenHeight : Math.round(Dimensions.get('window').height),
  screenWidth : Math.round(Dimensions.get('window').width),
  imagesIce : [
    require("../assets/images/ice/1.png"),
    require("../assets/images/ice/2.png"),
    require("../assets/images/ice/3.png"),
    require("../assets/images/ice/4.png"),
    require("../assets/images/ice/5.png"),
    require("../assets/images/ice/6.png"),
    require("../assets/images/ice/7.png"),
    require("../assets/images/ice/8.png"),
    require("../assets/images/ice/9.png"),
    require("../assets/images/ice/10.png"),
    require("../assets/images/ice/11.png"),
    require("../assets/images/ice/12.png"),
    require("../assets/images/ice/13.png"),
    require("../assets/images/ice/14.png"),
    require("../assets/images/ice/15.png"),
    require("../assets/images/ice/16.png"),
    require("../assets/images/ice/17.png"),
    require("../assets/images/ice/18.png"),
    require("../assets/images/ice/19.png"),
    require("../assets/images/ice/20.png"),
    require("../assets/images/ice/21.png"),
    require("../assets/images/ice/22.png"),
    require("../assets/images/ice/23.png"),
    require("../assets/images/ice/24.png"),
    require("../assets/images/ice/25.png"),
  ],

  imagesSeal : [
    require("../assets/images/seal/1.png"),
    require("../assets/images/seal/2.png"),
    require("../assets/images/seal/3.png"),
    require("../assets/images/seal/4.png"),
    require("../assets/images/seal/5.png"),
  ],

  imagesBear : [
    require("../assets/images/bear/1.png"),
    require("../assets/images/bear/2.png"),
    require("../assets/images/bear/3.png"),
    require("../assets/images/bear/4.png"),
    require("../assets/images/bear/5.png"),
  ],

  imagesPinguin : [
    require("../assets/images/bear/1.png"),
    require("../assets/images/bear/2.png"),
    require("../assets/images/bear/3.png"),
    require("../assets/images/bear/4.png"),
    require("../assets/images/bear/5.png"),
  ],

  pinguinsPosition:[
    [2,2],[2,3],[2,4],[2,5],[2,6],[2,7],[2,8],
    [3,2],[3,3],[3,4],[3,5],[3,6],[3,7],[3,8],
    [4,2],[4,3],[4,4],[4,5],[4,6],[4,7],[4,8],
    [5,2],[5,3],[5,4],[5,5],[5,6],[5,7],[5,8],
    [6,2],[6,3],[6,4],[6,5],[6,6],[6,7],[6,8],
    [7,2],[7,3],[7,4],[7,5],[7,6],[7,7],[7,8],
  ],

  icebergsPosition:[
    {ices:[true,true,true,true,true,true,true,true,true,true], position:10},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:9},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:8},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:7},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:6},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:5},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:4},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:3},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:2},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:1},
    {ices:[true,true,true,true,true,true,true,true,true,true], position:0},
  ],

  textSeal : [
    "Guy, you sucks ...",
    "I never seen someone as bad.",
    "I cannot count on you",
    "Just stop this game, it's too difficult for you",
    "Don't try again, let me die !",
    "You really are a disaster",
    "My grand mother seal is better than you",
    "Please do better, you are so bad",
    "Are you blind ? It was so easy",
    "Crap, you play like a snail",
    "Forget this game, not for you",
    "You will never win this game, sorry"
  ],

  textBear : [
    "Damn looser",
    "You are the worst player I ever seen",
    "Polar bear will die because of you",
    "I'm not joking, stop to ridicule yourself",
    "Finally, you'r not so bad, in an other life",
    "Antartic will totally melt before you win this game",
    "You make me laught",
    "Hopefully, you can't be worst next time you play",
    "My brother is 2 year old, but better than you",
    "One polar bear less, since I will kill myself to not see you play again",
    "Fortunately, I will never cross you in real life",
    "Water wets, fire burn, and you loose"

  ],

  textPinguin : [
    "You look tired ?",
    "Not again...",
    "Stop, stop please !",
    "Last person who made this score was a baby",
    "It's hurt to see that disaster",
    "Sometime, we dream that you stop playing",
    "All pinguin in the world will come to kick your ass",
    "You stink. Really.",
    "Impossible, you loose again, no way !",
    "Bravo, this score is still shity",
    "I don't have any words to describe as poor you are",
    "Fail. You failed. You failed again. And again."
  ],

  textWhale : [
    "Are you sick ? go to sleep bitch",
    "That's nasty",
    "Poor person, you are nothing but a looser",
    "nothing to say...",
    "Whale will have arms before you win",
    "Sorry, you failed",
    "little pussy, it's though so simple",
    "___",
    "Impossible, you loose again, no way !",
    "Bravo, this score is still shity",
    "I don't have any words to describe as poor you are",
    "Fail. You failed. You failed aagin. And again."
  ],

  images1 : [
    require("../assets/images/1/1.png"),
    require("../assets/images/1/2.png"),
    require("../assets/images/1/3.png"),
    require("../assets/images/1/4.png"),
    require("../assets/images/1/5.png"),
    require("../assets/images/1/6.png"),
    require("../assets/images/1/7.png"),
    require("../assets/images/1/8.png"),
    require("../assets/images/1/9.png"),
    require("../assets/images/1/10.png"),
    require("../assets/images/1/11.png"),
    require("../assets/images/1/12.png"),
    require("../assets/images/1/13.png"),
    require("../assets/images/1/14.png"),
    require("../assets/images/1/15.png"),
    require("../assets/images/1/16.png"),
    require("../assets/images/1/17.png"),
    require("../assets/images/1/18.png"),
    require("../assets/images/1/19.png"),
    require("../assets/images/1/20.png"),
    require("../assets/images/1/21.png"),
    require("../assets/images/1/22.png"),
    require("../assets/images/1/23.png"),
    require("../assets/images/1/24.png"),
    require("../assets/images/1/25.png"),
  ],

  images2 : [
    require("../assets/images/2/1.png"),
    require("../assets/images/2/2.png"),
    require("../assets/images/2/3.png"),
    require("../assets/images/2/4.png"),
    require("../assets/images/2/5.png"),
    require("../assets/images/2/6.png"),
    require("../assets/images/2/7.png"),
    require("../assets/images/2/8.png"),
    require("../assets/images/2/9.png"),
    require("../assets/images/2/10.png"),
    require("../assets/images/2/11.png"),
    require("../assets/images/2/12.png"),
    require("../assets/images/2/13.png"),
    require("../assets/images/2/14.png"),
    require("../assets/images/2/15.png"),
    require("../assets/images/2/16.png"),
    require("../assets/images/2/17.png"),
    require("../assets/images/2/18.png"),
    require("../assets/images/2/19.png"),
    require("../assets/images/2/20.png"),
    require("../assets/images/2/21.png"),
    require("../assets/images/2/22.png"),
    require("../assets/images/2/23.png"),
    require("../assets/images/2/24.png"),
    require("../assets/images/2/25.png"),
  ],

  images3 : [
    require("../assets/images/3/1.png"),
    require("../assets/images/3/2.png"),
    require("../assets/images/3/3.png"),
    require("../assets/images/3/4.png"),
    require("../assets/images/3/5.png"),
    require("../assets/images/3/6.png"),
    require("../assets/images/3/7.png"),
    require("../assets/images/3/8.png"),
    require("../assets/images/3/9.png"),
    require("../assets/images/3/10.png"),
    require("../assets/images/3/11.png"),
    require("../assets/images/3/12.png"),
    require("../assets/images/3/13.png"),
    require("../assets/images/3/14.png"),
    require("../assets/images/3/15.png"),
    require("../assets/images/3/16.png"),
    require("../assets/images/3/17.png"),
    require("../assets/images/3/18.png"),
    require("../assets/images/3/19.png"),
    require("../assets/images/3/20.png"),
    require("../assets/images/3/21.png"),
    require("../assets/images/3/22.png"),
    require("../assets/images/3/23.png"),
    require("../assets/images/3/24.png"),
    require("../assets/images/3/25.png"),
  ],

  images4 : [
    require("../assets/images/4/1.png"),
    require("../assets/images/4/2.png"),
    require("../assets/images/4/3.png"),
    require("../assets/images/4/4.png"),
    require("../assets/images/4/5.png"),
    require("../assets/images/4/6.png"),
    require("../assets/images/4/7.png"),
    require("../assets/images/4/8.png"),
    require("../assets/images/4/9.png"),
    require("../assets/images/4/10.png"),
    require("../assets/images/4/11.png"),
    require("../assets/images/4/12.png"),
    require("../assets/images/4/13.png"),
    require("../assets/images/4/14.png"),
    require("../assets/images/4/15.png"),
    require("../assets/images/4/16.png"),
    require("../assets/images/4/17.png"),
    require("../assets/images/4/18.png"),
    require("../assets/images/4/19.png"),
    require("../assets/images/4/20.png"),
    require("../assets/images/4/21.png"),
    require("../assets/images/4/22.png"),
    require("../assets/images/4/23.png"),
    require("../assets/images/4/24.png"),
    require("../assets/images/4/25.png"),
  ]
}
