

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_KEYWORD = "ADD_KEYWORD";
export const RESET_CATEGORY = "RESET_CATEGORY";
export const RESET_KEYWORD = "RESET_KEYWORD";
export const SET_USEREMAIL = "SET_USEREMAIL";
export const SET_ACCOUNTSTATE = "SET_ACCOUNTSTATE";
export const SET_FRIENDSSTATE = "SET_FRIENDSSTATE";
export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const CONNECT = "CONNECT";
export const SELECT_SHEETMENU = "SELECT_SHEETMENU";
export const SET_NEW_BET = "SET_NEW_BET";
export const SET_BET_SELECTED = "SET_BET_SELECTED";
export const SET_BET_INACTIVE = "SET_BET_INACTIVE";
export const SET_WINNER = "SET_WINNER";
export const GET_USERBETS = "GET_USERBETS";
export const GET_USERFRIENDS = "GET_USERFRIENDS";
export const RESET_ACCOUNTSTATE = "RESET_ACCOUNTSTATE";
export const GET_USERWITNESSOF = "GET_USERWITNESSOF";
export const UPDATE_WITNESSOF = "UPDATE_WITNESSOF";
export const ACCEPT_BET = "ACCEPT_BET";
export const REPLACE_FRIEND = "REPLACE_FRIEND";
export const SET_BEST_SCORE = "SET_BEST_SCORE";
export const SET_BEST_SCORES = "SET_BEST_SCORES";
